movie:
  api:
    url: http://www.omdbapi.com/

springdoc:
  api-docs:
    enabled: false

security:
  jwt:
    url:
      signin: /v1/signin
      signup: /v1/signup
    token:
      secret: ${APPLICATION_JWT_SECRET}
      expiration: ${APPLICATION_JWT_TOKEN_EXPIRATION}

spring:
  profiles:
    active: prod
  jackson:
    serialization:
      indent_output: true
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: ${APPLICATION_JPA_HIBERNATE_DDL_AUTO}
    generate-ddl: ${APPLICATION_JPA_GENERATE_DDL}
  datasource:
    url: ${APPLICATION_JPA_DATASOURCE_URL}

logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: INFO

server:
  port: ${APPLICATION_PORT}

api:
  server:
    url: ${APPLICATION_URL}:${APPLICATION_PORT}

omdbapi:
  api:
    key: ${APPLICATION_OMDBAPI_KEY}
