movie:
  api:
    url: http://www.omdbapi.com/

# TODO REMOVE THE SERVLET PARAMETER BELOW AFTER REMOVING THE FILE UPLOAD ENDPOINT
spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  jpa:
    hibernate:
      ddl-auto: ${APPLICATION_JPA_HIBERNATE_DDL_AUTO}
    generate-ddl: ${APPLICATION_JPA_GENERATE_DDL}
  datasource:
    url: ${APPLICATION_JPA_DATASOURCE_URL}

server:
  port: ${APPLICATION_PORT}

api:
  server:
    url: ${APPLICATION_URL}

omdbapi:
  api:
    key: ${APPLICATION_OMDBAPI_KEY}

springdoc:
  api-docs:
    enabled: false

security:
  jwt:
    url:
      signin: /v1/signin
      signup: /v1/signup
    token:
      secret: ${APPLICATION_JWT_SECRET}
      expiration: ${APPLICATION_JWT_TOKEN_EXPIRATION}
