springdoc:
  api-docs:
    enabled: true

security:
  jwt:
    url:
      signin: /v1/signin
      signup: /v1/signup
    token:
      secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
      expiration: 86400000 # 24 hours

server:
  port: 8080

spring:
  jackson:
    serialization:
      indent_output: true
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
  datasource:
    url: jdbc:h2:mem:movietestdb;DB_CLOSE_DELAY=-1;NON_KEYWORDS=VALUE,YEAR,USER

omdbapi:
  api:
    key: f06bd2c1

api:
  server:
    url: ${http://localhost:${server.port}}
