movie:
  api:
    url: http://www.omdbapi.com/
  jpa:
    hibernate:
      ddl-auto: ${APPLICATION_JPA_HIBERNATE_DDL_AUTO}
    generate-ddl: ${APPLICATION_JPA_GENERATE_DDL}
  datasource:
    url: ${APPLICATION_JPA_DATASOURCE_URL}
  h2:
    console:
      enabled: false

server:
  port: ${APPLICATION_PORT}

api:
  server:
    url: ${APPLICATION_URL}

omdbapi:
  api:
    key: ${APPLICATION_OMDBAPI_KEY}

springdoc:
  api-docs:
    enabled: false

security:
  jwt:
    url:
      signin: /v1/signin
      signup: /v1/signup
    token:
      secret: ${APPLICATION_JWT_SECRET}
      expiration: ${APPLICATION_JWT_TOKEN_EXPIRATION}

spring:
  logging:
    level:
      root: INFO
