movie:
  api:
    url: http://www.omdbapi.com/

spring:
  jackson:
    serialization:
      indent_output: true
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

server:
  port: ${APPLICATION_PORT:8080}

api:
  server:
    url: ${APPLICATION_URL:http://localhost:${server.port}}

jwt:
  # This token must be encoded using Base64 with minimum 88 Bits (you can type `echo 'secret-key'|base64` on your command line)
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # token is valid 24 hours
  token-validity-in-seconds: 86400
