movie:
  api:
    url: http://www.omdbapi.com/

spring:
  jackson:
    serialization:
      indent_output: true
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

server:
  port: ${APPLICATION_PORT:8080}

api:
  server:
    url: ${APPLICATION_URL:http://localhost:${server.port}}

security:
  jwt:
    url:
      signin: /v1/signin
      signup: /v1/signup
    token:
      secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
      expiration: 86400000 # 24 hours
